volumes:
    db: {}
    cloudbeaver: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:16.3-alpine
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - .env
    cloudbeaver:
        container_name: ${PROJECT_NAME}-cloudbeaver
        image: dbeaver/cloudbeaver:latest
        ports:
            - 8978:8978
        volumes: 
            - cloudbeaver:/opt/cloudbeaver/workspace   
    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: ["air", "-c", ".air.toml"]
        volumes:
            - ./backend:/app
        ports:
          - 8080:8080
        env_file:
            - .env
    
        